# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Pay-As-You-Go (dc8919fb-5081-43f7-9f5b-0fd1ba659d96)'
    appType: 'webAppLinux'
    appName: 'testingdevopsrod'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'